Repository note629/KOSA_RPA3_2nd_Project, pull requests merged in 2023-08, with the labels that each got.

#1 Users Application에서 Login 기능 구현
  RecyclableProject/settings.py
  RecyclableProject/urls.py
  requirements.txt
  users/forms.py
  users/models.py
  users/static/css/cover.css
  users/templates/users/login.html
  users/urls.py
  users/views.py
Labels: enhancement

#4 Users 회원가입 기능 구현
  users/forms.py
  users/templates/users/login.html
  users/templates/users/signup.html
  users/urls.py
  users/views.py
Labels: enhancement

#5 로그인 여부에 따른 "nav" 로그인 / 로그아웃 표현 전환
  static/css/cover.css
  templates/base.html
Labels: enhancement

#6 로그아웃 구현
  users/urls.py
  users/views.py
Labels: enhancement

#7 "models.py"에 RecycleLog class 생성
  users/models.py
Labels: enhancement

#3 Qnaboard 기능구현만 작성
  RecyclableProject/urls.py
  qnaboard/admin.py
  qnaboard/forms.py
  qnaboard/models.py
  qnaboard/static/css/qna_list.css
  qnaboard/static/css/style.css
  qnaboard/templates/qnaboard/qna_create.html
  qnaboard/templates/qnaboard/qna_list.html
  qnaboard/urls.py
  qnaboard/views.py
  templates/base.html
Labels: enhancement

#9 feat: activity 앱 추가 및 user rank 기능 추가
  RecyclableProject/settings.py
  RecyclableProject/urls.py
  activity/__init__.py
  activity/admin.py
  activity/apps.py
  activity/migrations/__init__.py
  activity/models.py
  activity/templates/activity/maintest.html
  activity/templates/activity/ranktest.html
  activity/tests.py
  activity/urls.py
  activity/views.py
  users/admin.py
  users/models.py
Labels: enhancement

#11 "base.html"에 로그인/로그아웃 상태에 따른 "nav" 전환 등
  templates/base.html
Labels: enhancement

#12 feat: "storemap" Kakao API를 이용해서 지도 구현
  RecyclableProject/settings.py
  RecyclableProject/urls.py
  static/css/cover.css
  static/js/storemap.js
  storemap/templates/storemap/zerobasemap.html
  storemap/urls.py
  storemap/views.py
  templates/base.html
Labels: enhancement

#13 Classify
  classify/views.py
  media/classify_img/242135_01001_220720_P1_T1.jpg
  media/recycle_img/242135_01001_220720_P1_T1.jpg
  storemap/__init__.py
  storemap/admin.py
  storemap/apps.py
  storemap/migrations/__init__.py
  storemap/models.py
  storemap/tests.py
  storemap/views.py
Labels: fix

#27 User에서 변경 수정 사항
  static/css/cover.css
  static/css/recycle_chart_css.css
  templates/home.html
  users/forms.py
  users/views.py
Labels: enhancement, fix

#28 feat: "classify" application에서 이미지 Drag n Drop 기능 추가
  classify/forms.py
  classify/templates/classify/classify.html
  classify/templates/classify/classify_result.html
  classify/views.py
  static/css/classify.css
  static/css/recycle_chart_css.css
  static/js/classify.js
  users/templates/users/change_password.html
  users/templates/users/mypage.html
Labels: enhancement

#29 feat: "gallery" application에서 gallery 기능 추가
  activity/models.py
  activity/templates/activity/gallery.html
  activity/urls.py
  activity/views.py
  classify/templates/classify/classify_result.html
  classify/urls.py
  classify/views.py
  static/css/gallery.css
  static/js/gallery.js
  static/js/recycle_chart_js.js
  templates/base.html
  users/views.py
Labels: enhancement

#32 Activity
  activity/urls.py
  activity/views.py
  static/css/button.css
  static/css/cover.css
  static/css/gallery.css
  static/css/home_action.css
  static/css/login.css
  static/css/recycle_chart_css.css
  storemap/views.py
  templates/base.html
  users/forms.py
  users/templates/users/login.html
  users/templates/users/signup.html
Labels: fix

#34 All board
  noticeboard/forms.py
  noticeboard/templates/noticeboard/notice_create.html
  noticeboard/templates/noticeboard/notice_list.html
  noticeboard/templates/noticeboard/notice_read.html
  noticeboard/templates/noticeboard/notice_update.html
  qnaboard/forms.py
  qnaboard/templates/qnaboard/qna_create.html
  qnaboard/templates/qnaboard/qna_list.html
  qnaboard/templates/qnaboard/qna_read.html
  qnaboard/templates/qnaboard/qna_update.html
  qnaboard/views.py
  static/css/board_create.css
  static/css/board_list.css
  static/css/board_read.css
  static/css/board_update.css
Labels: enhancement, fix

#35 All board
  noticeboard/templates/noticeboard/notice_create.html
  noticeboard/templates/noticeboard/notice_list.html
  noticeboard/templates/noticeboard/notice_read.html
  noticeboard/views.py
  qnaboard/templates/qnaboard/qna_list.html
  qnaboard/views.py
  static/css/board_read.css
Labels: fix
